### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by mauringo** [lg-lima1/snap-ctrlx-iot#1]
Hi @lg-lima1 

Really thanks for Your Repo!! It's just perfect.

**Comment by lg-lima1** [comment]
Hi @mauringo !
Good to know that you liked it. Feel free to add any suggestions.

**Comment by mauringo** [comment]
In my opinion it's just perfect.

To be the best snap in the world I think i would add:
Mongodb
Mosquitto 
A webserver with a simple prompt to enable/disable services.

I would additionally store all the data in the $SNAP_COMMON directory to maintain db data across updates. 

But by the way it's already more than complete.

**Comment by lg-lima1** [comment]
I've updated the project with several additional functionalities, including your suggestion for storing InfluxDB data on $SNAP_COMMON.
