### ISSUE TITLE
Access to Grafana and Node Red Flows

### ISSUE THREAD

**Issue by PLukomski** [lg-lima1/snap-ctrlx-iot#2]
Hello,

I downloaded and installed your app on my CtrlX Core.  However, when I click on Node-Red Flows I get an error page stating the site cannot be reached.  The address it tries to go to is the <IP Address of CtrlX Core>:1880.  I already have the Node-Red app from Rexroth installed on my CtrlX core and when I go through that app it takes me to <IP Address of CtrlX Core>/node-red.  What am I missing to open the node red flows from your app?

I get the same message when I click on the Grafana dashboard button.  It tries to go to <IP Address of CtrlX Core>:3000.  I get a message stating the site cannot be reached.  

If you have any other write on this I'd love to see more info.  We are looking at using this exact config for a customer and this apps seems like it could simplify things.  Thanks!

**Comment by lg-lima1** [comment]
Hi!
I've seen this error before in previous versions. Please, what version of the app are you using? Is it on a real device or on ctrlX Core Virtual? Have you already tried uninstalling the Rexroth official Node RED app? (maybe some conflict?)
I'll try my best to solve this.

**Comment by PLukomski** [comment]
Luiz,

I'm using a physical CtrlX Core.  I will try uninstalling the Rexroth Node Red app.  I'll shoot you an email on your gmail account as it will be easier to communicate that way.  Thanks for the quick response.
