### ISSUE TITLE
Ctrlx core20?

### ISSUE THREAD

**Issue by Open1333** [lg-lima1/snap-ctrlx-iot#3]
Hello does this support Ctrlx core20?

**Comment by lg-lima1** [comment]
Yes, but you have to manually install core18 snap.

Em ter., 12 de jul. de 2022 05:38, Open1333 ***@***.***>
escreveu:

**Comment by Open1333** [comment]
Thank you for your fast reply, do you know where can I find core18 snap file?

**Comment by Open1333** [comment]
I managed to find core18 snap file but i am not able to enter into influxdb.

**Comment by Open1333** [comment]
I found my core18 snap file thanks is working!

**Comment by lg-lima1** [comment]
The app now has support for core20. You don't need additional installation of the core18 snap anymore.
